site_name: EGDPG Documentation Suite
theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  logo: images/logo.png

extra:
  generator: false

nav:
  - Home: index.md
  - Modular Character Preview:
      - Overview: preview-plugin/index.md
      - Features: preview-plugin/features.md
      - Installation: preview-plugin/installation.md
      - Integrations: preview-plugin/integrations.md
      - Patch Notes: preview-plugin/patch_notes.md
  - Modular WIP Plugin:
      - Coming Soon: second-plugin/index.md
  - Shared Resources:
      - FAQ: shared/faq.md
      - Support: shared/support.md
